version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
        auth:
          username: rkiryushkkin
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13

      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t rkiryushkkin/circleci:$TAG .
          docker login -u rkiryushkkin -p $DOCKERHUB_PASSWORD
          docker push rkiryushkkin/circleci:$TAG
